# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
        "project_info": {
           "project_number": "244145628679",
    "project_id": "http://httpsrathanaphonwebsitecoin.firebaseapp.com/"
    "storage_bucket": "http://httpsrathanaphonwebsitecoin.firebaseapp.com/.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:244145628679:android:a7f10297db1a854b396ca2",
        "android_client_info": {
          "package_name": "http://httpsrathanaphonwebsitecoin.firebaseapp.com/"
        }
      },
      "oauth_client": [
        {
          "client_id": "244145628679-5lpa61gqs6naujcec6om73v6hbhrlpq7.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "AIzaSyAZwzbBslhqIFIc2c2-wJRru9PRcwpeu7I"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "244145628679-5lpa61gqs6naujcec6om73v6hbhrlpq7.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "2"
}
